### ISSUE TITLE
eid=7&text=no proxy device provided error after firmware update

### ISSUE THREAD

**Issue by jazzerjazzer** [ping13/heospy#22] opened 2022-07-28 10:19 UTC
Hi, first of all thanks for writing such a nice wrapper! 

I tried to run it when my leading device was a HEOS AMP HS2 but I kept getting the following error: 
```
{
  "heos": {
    "command": "",
    "result": "fail",
    "message": "eid=7&text=no proxy device provided"
  },
  "heos_message_parsed": {
    "eid": "7",
    "text": "no proxy device provided"
  }
}
```

Then I switched to my HEOS Link and it worked perfectly, also on my HEOS 5. 
However, when I updated the firmware of HEOS Link to latest I started getting the exact same error, no matter which command I tried to run. 

I was wondering if anyone also faced the same issue, if yes I'd be interested in hearing how to fix it. 
Thanks in advance!

**Comment by ping13** [comment] 2022-08-15 05:33
Sorry, I cannot reproduce this with my old hardware (HEOS 1, HEOS 3). I do have problems with the latest updates, but this is not related to `heospy`, but in combination with Spotify - I'm thinking of abandoning the HEOS speakers - they have become too unreliable for me.

**Comment by olalid** [comment] 2022-11-27 19:01
I was chasing the same problem, but eventually it just started working again after I rebooted all of my HEOS devices. Rebooting just the one where I got the error message "no proxy device provided" did not help, I had to reboot all the others too.

**Comment by ping13** [comment] 2022-12-18 14:59
Thanks, I close the issue.

**Closed as completed** 2022-12-18 14:59 UTC
